// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using api.Infrastructure.Persistence;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501120000_SyncUsersTableColumns")]
    partial class SyncUsersTableColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot AppDbContextModelSnapshot.cs dosyasında yönetilmektedir.
            // Bu migration yalnızca ham SQL kolon ekleme işlemi gerçekleştirir.
        }
    }
}