// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using api.Infrastructure.Persistence;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501000000_AddAccountStatusToUsers")]
    partial class AddAccountStatusToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot is maintained in AppDbContextModelSnapshot.cs
            // This migration only performs a raw SQL column addition.
        }
    }
}